name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Initialize submodules
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          CF_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        run: |
          git config --global url."https://radoslawg:${GITEA_TOKEN}@gitea.grzanka.org/".insteadOf "git@gitea.grzanka.org:"
          git config --global --add http."https://gitea.grzanka.org/".extraheader "CF-Access-Client-Id: ${CF_CLIENT_ID}"
          git config --global --add http."https://gitea.grzanka.org/".extraheader "CF-Access-Client-Secret: ${CF_CLIENT_SECRET}"
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libx11-dev libxxf86vm-dev libgl1-mesa-dev libudev-dev libvulkan-dev

      - name: Build project
        run: cargo build

      - name: Run tests
        run: cargo test

